function(lto_setup)
    if (${CMAKE_BUILD_TYPE} MATCHES "Release" OR ${CMAKE_BUILD_TYPE} MATCHES "RelWithDebInfo")
      include(CheckIPOSupported)
      check_ipo_supported(RESULT result OUTPUT output)
      if (result)
        set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON PARENT_SCOPE)
      else ()
        message(WARNING "IPO is not supported: ${output}")
      endif ()
    endif()
endfunction()
